spring:
  application:
    name: eureka-server
server:
  port: 10001
eureka:
  instance:
    hostname: 127.0.0.1
#    ip-address: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }) %clr(%-40.40logger{39}){cyan} %L %clr(:){faint}  %n${LOG_EXCEPTION_CONVERSION_WORD:%m}%n"
  file: ${spring.application.name}.log
#spring.application.name=eureka-server
#server.port=10001
#
#eureka.instance.hostname=localhost
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#
#logging.file=${spring.application.name}.log