spring:
  application:
    name: config-client
  datasource:
    url: 127.0.0.1:3306
    password: "{cipher}AQBSi9ruqdLeX7ZAs44BuXOKMK5NxD50GWHe3bm3OKXcdT8A8SPEexuwSztiSVA+c3lEActk0ZiHAtRH9+TD0FGjQmHZX2VkM/DNwUCRk9YsX2CXCUFE98PlEJP0dyZAwTXTRx2Mpy2rV43ZBQ5Q+ymCU4xNabwOVhOFXn8DyaBN+qcLzrvfDg4MjSTrz0Wz/vEC3pFxmmxo1zo65bbnGO6lyZYtztKa4owlF25NgMn2YuxhV9AoqgHTCuXmRYBOF/f0tmoCY06i1QZmwbWKFg31IK3QMvBAuSPeoZHRA4gKrsL6+rzzRWKKkRPd+b4hAhdIBWAZ/OhUCOoKJh7nLhknAnXiaU99tiR5KSquJd7Bas9GF5thZZ7h89fkii3K/Oo="
    name: test
    username: zqw

server:
  port: 10013
eureka:
  client:
    service-url:
      {"defaultZone":"http://127.0.0.1:10001/eureka/"}
logging:
  file: ${spring.application.name}.log
  path: d:/aa/
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }) %clr(%-40.40logger{39}){cyan} %L %clr(:){faint}  %n${LOG_EXCEPTION_CONVERSION_WORD:%m}%n"
    